# Generated by Django 5.0.6 on 2025-02-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('puntos', models.IntegerField(default=0)),
            ],
        ),
    ]
