# Generated by Django 5.0.6 on 2025-02-10 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_casa', models.IntegerField()),
                ('goles_visita', models.IntegerField()),
                ('equipo_casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_casa', to='liga.equipo')),
                ('equipo_visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_visita', to='liga.equipo')),
            ],
        ),
    ]
