# Generated by Django 5.0.6 on 2025-02-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0002_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='nombre_completo',
            field=models.CharField(max_length=100),
        ),
    ]
