# Generated by Django 5.0.6 on 2025-02-24 19:49

import productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[productos.models.validar_precio]),
        ),
    ]
