# Generated by Django 5.0.6 on 2025-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfilusuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
