# Generated by Django 5.0.6 on 2025-02-10 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nickname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_acceso', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
