# Generated by Django 5.0.6 on 2025-02-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100)),
                ('renta', models.FloatField()),
                ('edad', models.IntegerField()),
                ('puntuacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
